set number
set mouse=a
syntax enable
set showcmd
set encoding=utf-8
set showmatch
set relativenumber
set sw=2

call plug#begin('~/.vim/plugged')
"Tema 
Plug 'morhetz/gruvbox'
"Status and theme (ej: normal, insert, etc.)
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
"Autocomplete
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'}
"Nvim R
Plug 'jalvesaq/Nvim-R', {'branch': 'stable'}
"NerdTREE
Plug 'preservim/nerdtree'
call plug#end()

"--------- -- -------- -- --------

"Tema color - configuracion
set background=dark
colorscheme gruvbox

"Vim airlane - theme
let g:airline_theme='luna'
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
"NerdTREE 
nnoremap <C-n> :NERDTree<CR>
"Otros
let g:coc_disable_startup_warning = 1

" R

" press -- to have Nvim-R insert the assignment operator: <-
let R_assign_map = "--"

" set a minimum source editor width
let R_min_editor_width = 80

" make sure the console is at the bottom by making it really wide
let R_rconsole_width = 1000

" show arguments for functions during omnicompletion
let R_show_args = 1

" Don't expand a dataframe to show columns by default
let R_objbr_opendf = 0

" Press the space bar to send lines and selection to R console
vmap <Space> <Plug>RDSendSelection
nmap <Space> <Plug>RDSendLine
