# ---------------------------- #
# Author: Paula Andrea Amado
# Maintainers:
# Date: Dec 6, 2022
# ---------------------------- #

#------------------------Prompt Custom------------------ #
PS1='🐈‍⬛ %F{#EF476F}%n%f at 🐈‍⬛ %F{#FFD166}%m%f: 🐾%F{#F3C677}%~/%f '

#------------------------Aliases------------------------- #
alias gs="git status"
alias gc="git commit -m"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

#-----------------------Config-------------------------- #
set number
set showcmd
set encoding=utf-8

#------------------------Path------------------------------#
source $HOME/mydotfiles/shell/paths
export LC_ALL='en_US.UTF-8'
# Done

